name: ci

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - working-directory: practice2025
      run: dotnet build
    - working-directory: practice2025
      run: dotnet test